FROM centos:7

# Install OS packages
RUN yum -y update
RUN yum install -y epel-release
RUN yum install -y python36 python36-devel python36-setuptools
RUN yum clean all

RUN ln -s /usr/bin/python3.6 /usr/bin/python3
RUN python3 -m ensurepip
RUN python3 -m pip install --upgrade pip

# Create a director for the application
RUN mkdir /app
WORKDIR /app

# Install Python packages
COPY ./requirements.txt /app/requirements.txt
RUN pip3 --no-cache-dir install -r requirements.txt

# Copy source code
COPY ./ /app

# Run application
CMD ["python3", "/app/app.py"]

EXPOSE 80 80
